## **Arrays en Numpy**

In [40]:
import numpy as np

#np.arange
rango_array = np.arange(5)
print("Rango array:", rango_array)
print("Rango específico array:", np.arange(2, 10)) #Incluye el primer elemento y excluye el segundo
print("Array con paso personalizado:", np.arange(0, 10, 2)) #Empieza del 0, sin incluir el 10, con salto de 2
print("Array con paso decimal:", np.arange(0, 1, 0.2))
print("Array en orden inverso:", np.arange(10, 0, -1))

# Array de números aleatorios
random_array = np.random.random((2, 2)) #Con random, valores entre 0 y 1 y hay que especificar dimensiones entre paréntesis 
print("\nArray de números aleatorios:\n", random_array)
random_array_argumentos = np.random.rand(2, 3) #Es igual pero las dimensiones se pasan como parámetros

# Array de números aleatorios enteros
random_int_array = np.random.randint(0, 10, (2, 3)) #np.random.randint(0, 10, size=(2, 3)). No incluiría el 10
print("Array de números aleatorios enteros:\n", random_int_array)

# Array con valores espaciados
linspace_arr = np.linspace(0, 1, 5) # Empieza en 0, termina en 1, con 5 puntos en total
print("Array con valores espaciados", linspace_arr)

array = np.arange(12)  # [0, 1, ..., 11]
reshaped = array.reshape(2, 6) #Convierte el array unidimensional en una matriz 2x6
print("Array reshape (2x6):\n", reshaped)

# Convertir a 1D
flattened = reshaped.ravel()
print("Array aplanado:", flattened)

# Transponer el array
transposed = reshaped.T #Transpone la matriz 2x6 intercambiando filas por columnas. Lo que estaba en horizontal pasa a estar en vertical y viceversa.
print("Array transpuesto:\n", transposed)
  

Rango array: [0 1 2 3 4]
Rango específico array: [2 3 4 5 6 7 8 9]
Array con paso personalizado: [0 2 4 6 8]
Array con paso decimal: [0.  0.2 0.4 0.6 0.8]
Array en orden inverso: [10  9  8  7  6  5  4  3  2  1]

Array de números aleatorios:
 [[0.44690161 0.97799527]
 [0.64701594 0.12144132]]
Array de números aleatorios enteros:
 [[1 3 0]
 [2 5 4]]
Array con valores espaciados [0.   0.25 0.5  0.75 1.  ]
Array reshape (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Array aplanado: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array transpuesto:
 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


### **Indexación de Arrays**

In [ ]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])

# Indexación en un array 2D
print(arr_2d[0, 0]) # Elemento de la primera fila, primera columna
print(arr_2d[1, 2]) # Elemento de la segunda fila, tercera columna
print(arr_2d[-1, -1]) # Último elemento de la última fila

# Selección de filas y columnas en un array 2D 
print(arr_2d[0, :]) # Primera fila, todas las columnas
print(arr_2d[:, 1]) # Segunda columna, todas las filas

1
6
9
[1 2 3]
[2 5 8]


### **Slicing de Arrays**

In [ ]:
array = np.arange(10)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print("Slice [2:6]:", array[2:6]) #Empieza por el elemento[2] del array, y acaba en el elemento [6] excluyéndolo.

# Slice con un paso de 2
print("Slice [::2]:", array[::2]) #Empieza en el principio, llega hasta el final, y salta de 2 en 2 -> [0, 2, 4, 6, 8]

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Slice de las primeras dos filas y dos columnas:\n", array_2d[:2, :2]) #Desde el principio hasta el elemento [2] en las filas, y luego igual sobre las columnas de esas filas. 

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  #Dimensión 0
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]], #Dimensión 1
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]] #Dimensión 2
])
print("\Primera dimensión:\n", array_3d[0])

# Slice: Seleccionar la primera fila de cada bloque
print("\nPrimera fila de cada bloque:\n", array_3d[:, 0, :]) #:Selecciona todos los bloques, 0 selecciona la primera fila de cada bloque, : selecciona todas las columnas.

# Slice: Seleccionar la primera columna de cada bloque
print("\nPrimera columna de cada bloque:\n", array_3d[:, :, 0])

# Slice: Seleccionar un elemento específico (bloque 2, fila 1, columna 2)
print("\nElemento en (2, 1, 2):", array_3d[2, 1, 2])  # 24


Slice [2:6]: [2 3 4 5]
Slice [::2]: [0 2 4 6 8]
Slice de las primeras dos filas y dos columnas:
 [[1 2]
 [4 5]]
\Primera dimensión:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Primera fila de cada bloque:
 [[ 1  2  3]
 [10 11 12]
 [19 20 21]]

Primera columna de cada bloque:
 [[ 1  4  7]
 [10 13 16]
 [19 22 25]]

Elemento en (2, 1, 2): 24
